version: '3'
services:
  redux-typescript:
    build: .
    environment:
      - "NODE_ENV=development"
    volumes:
      - ./:/usr/app
    command: sh -c 'cd redux-typescript && yarn start'
    ports:
      - '3000:3000'
    tty: true