version: '3'
services:
  twitter-clone:
    build: .
    environment:
      - "NODE_ENV=development"
    volumes:
      - ./:/usr/app
    command: sh -c 'cd twitter-clone && yarn start'
    ports:
      - '3000:3000'
    tty: true